nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/': ~

# FOSRest Configuration
fos_rest:
  routing_loader:
      default_format: json
  body_converter:
      enabled: true
      validate: true
  body_listener:
      enabled: true
      decoders:
          json: fos_rest.decoder.json
  format_listener:
    rules:
        - { path: '^/api', priorities: [json], fallback_format: json, prefer_extension: false }
        - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: false }
  param_fetcher_listener: force
  view:
    view_response_listener: force
    formats:
        json: true
        html: true